FROM nvcr.io/nvidia/pytorch:25.11-py3

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    git \
    python3-dev \
    python3-pip \
    libopenexr-dev \
    libxi-dev \
    libglfw3-dev \
    libglew-dev \
    libomp-dev \
    libxinerama-dev \
    libxcursor-dev \
    gdb \
    tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN pip uninstall xgboost transformer_engine flash_attn pynvml opencv-python-headless -y && \
    pip install --no-cache-dir vllm==0.15.1 && \
    pip install --no-cache-dir https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.7.16/flash_attn-2.8.3+cu130torch2.9-cp312-cp312-linux_x86_64.whl

CMD ["/bin/bash"]